[project]
name = "pystock"
version = "0.1.0"
description = "A Python package that that's help me to better invest in the stock market."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "pyomo>=6.8.0",
    "ruff>=0.7.2",
    "yfinance>=0.2.48",
]
